"""empty message

Revision ID: 10797c9d7ec3
Revises: 820e7b056cec
Create Date: 2016-11-30 00:34:17.817533

"""

# revision identifiers, used by Alembic.
revision = '10797c9d7ec3'
down_revision = '820e7b056cec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'soi')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('soi', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
