"""empty message

Revision ID: 6ab5e82658fa
Revises: e40f42201c74
Create Date: 2016-11-30 08:08:49.174926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab5e82658fa'
down_revision = 'e40f42201c74'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('instructor_name', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'instructor_name')
    ### end Alembic commands ###
