"""empty message

Revision ID: a8473ee33091
Revises: 
Create Date: 2016-11-30 07:03:25.338975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8473ee33091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_color', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'course_color')
    ### end Alembic commands ###
