"""empty message

Revision ID: e40f42201c74
Revises: a8473ee33091
Create Date: 2016-11-30 07:45:31.271746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40f42201c74'
down_revision = 'a8473ee33091'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'course_color')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_color', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
