"""empty message

Revision ID: e702a1d74bf6
Revises: None
Create Date: 2016-11-30 01:22:58.700663

"""

# revision identifiers, used by Alembic.
revision = 'e702a1d74bf6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'questions_question_owner_fkey', 'questions', type_='foreignkey')
    op.add_column('users', sa.Column('soi', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'soi')
    op.create_foreign_key(u'questions_question_owner_fkey', 'questions', 'users', ['question_owner'], ['username'])
    ### end Alembic commands ###
